from enum import Enum

class XbbRefTypeEnum(Enum):
    SYSTEM = (0, "enum.xbbRefType.name.system", "system")
    CRM = (1, "enum.xbbRefType.name.crm", "CRM")
    JXC = (2, "enum.xbbRefType.name.jxc", "JXC")
    WORK_ORDER_CENTER = (3, "enum.xbbRefType.name.work_order_center", "workOrderCenter")
    PAAS = (4, "enum.xbbRefType.name.paas", "paas")
    PAAS_SUBFORM = (100301, "enum.xbbRefType.name.paas", "paasSubform")
    PAAS_TEAM = (100302, "enum.xbbRefType.name.paas_team", "paasTeam")
    MARKET_MANAGEMENT = (5, "enum.xbbRefType.name.market_management", "marketManagement")
    ORDER_CENTER = (6, "enum.xbbRefType.name.order_center", "orderCenter")
    DISTRIBUTOR = (7, "enum.xbbRefType.name.distributor", "distributor")
    PROJECT_MANAGEMENT = (9, "enum.xbbRefType.name.projectManagement", "projectManagement")
    UNKNOWN = (404, "enum.xbbRefType.name.unknown", "unknown")
    CUSTOMER_MANAGEMENT = (100, "enum.xbbRefType.name.customer_management", "customerManagement")
    CUSTOMER = (101, "enum.xbbRefType.name.customer", "customer")
    CUSTOMER_FOCUS = (102, "enum.xbbRefType.name.customer_focus", "customerFocus")
    CUSTOMER_DEAL = (103, "enum.xbbRefType.name.customer_deal", "customerDeal")
    CUSTOMER_FOLLOW = (104, "enum.xbbRefType.name.customer_follow", "customerFollow")
    CUSTOMER_PUBLIC = (105, "enum.xbbRefType.name.customer_public", "customerPublic")
    CUSTOMER_RECYCLE = (106, "enum.xbbRefType.name.customer_recycle", "customerRecycle")
    CUSTOMER_NEARBY = (107, "enum.xbbRefType.name.customer_nearby", "customerNearby")
    CUSTOMER_STAGE = (108, "enum.xbbRefType.name.customer_stage", "customerStage")
    CUSTOMER_DUPLICATE = (109, "enum.xbbRefType.name.customer_duplicate", "customerDuplicate")
    CUSTOMER_BACK_REMIND = (110, "enum.xbbRefType.name.customer_back_remind", "customer_back_remind")
    CUSTOMER_REMIND = (111, "enum.xbbRefType.name.customer_remind", "customerRemind")
    CUSTOMER_TEAM = (112, "enum.xbbRefType.name.customer_team", "customerTeam")
    CUSTOMER_INDEX = (113, "enum.xbbRefType.name.customer_index", "customerIndex")
    CUSTOMER_SUBFORM = (114, "enum.xbbRefType.name.customer_subform", "customerSubform")
    CUSTOMER_TRANSFER = (115, "enum.xbbRefType.name.customer_transfer", "customerTransfer")
    CUSTOMER_TRANSFER_REMIND = (116, "enum.xbbRefType.name.customer_transfer_remind", "customerTransferRemind")
    CUSTOMER_STAGE_LOG = (117, "enum.xbbRefType.name.customer_stage_log", "customerStageLog")
    CONTRACT = (201, "enum.xbbRefType.name.contract", "contract")
    REFUND = (202, "enum.xbbRefType.name.refund", "refund")
    CONTRACT_REMIND = (203, "enum.xbbRefType.name.contract_remind", "contractRemind")
    CONTRACT_PRODUCT = (204, "enum.xbbRefType.name.contract_product", "contract_product")
    CONTRACT_TEAM = (205, "enum.xbbRefType.name.contract_team", "contractTeam")
    CONTRACT_PERFORMANCE = (206, "enum.xbbRefType.name.contract_performance", "contract_performance")
    REFUND_TEAM = (207, "enum.xbbRefType.name.refund_team", "refundTeam")
    REFUND_SUBFORM = (208, "enum.xbbRefType.name.refund_subform", "refundSubform")
    CONTRACT_SUBFORM = (209, "enum.xbbRefType.name.contract_subform", "contractSubform")
    CONTRACT_STAGE = (210, "enum.xbbRefType.name.contract_stage", "contractStage")
    SALES_OPPORTUNITY = (301, "enum.xbbRefType.name.sales_opportunity", "salesOpportunity")
    ALL_OPPORTUNITY = (302, "enum.xbbRefType.name.all_opportunity", "allOpportunity")
    KEY_OPPORTUNITY = (303, "enum.xbbRefType.name.key_opportunity", "keyOpportunity")
    SALE_STAGE = (304, "enum.xbbRefType.name.sale_stage", "saleStage")
    SALES_OPPORTUNITY_TEAM = (305, "enum.xbbRefType.name.sales_opportunity_team", "salesOpportunityTeam")
    SALES_OPPORTUNITY_PRODUCT = (306, "enum.xbbRefType.name.sales_opportunity_product", "salesOpportunityProduct")
    SALES_OPPORTUNITY_SUBFORM = (307, "enum.xbbRefType.name.sales_opportunity_subform", "salesOpportunitySubform")
    SALES_OPPORTUNITY_DUPLICATE = (308, "enum.xbbRefType.name.sales_opportunity_duplicate", "salesOpportunityDuplicate")
    OPPORTUNITY_STAGE_LOG = (309, "enum.xbbRefType.name.opportunity_stage_log", "opportunityStageLog")
    CONTACT = (401, "enum.xbbRefType.name.contact", "contact")
    CONTACT_TEAM = (402, "enum.xbbRefType.name.contact_team", "contactTeam")
    CONTACT_SUBFORM = (403, "enum.xbbRefType.name.contact_subform", "contactSubform")
    CONTACT_DUPLICATE = (405, "enum.xbbRefType.name.contact_duplicate", "contactDuplicate")
    PROJECT_DECISION_INFO = (406, "enum.xbbRefType.name.project_decision_info", "projectDecisionInfo")
    CUSTOMER_COMMUNICATE = (501, "enum.xbbRefType.name.customer_communicate", "customerCommunicate")
    SUPPLIER_COMMUNICATE = (502, "enum.xbbRefType.name.supplier_communicate", "supplierCommunicate")
    DETAIL_CUSTOMER_COMMUNICATE = (503, "enum.xbbRefType.name.detail_customer_communicate", "detailCustomerCommunicate")
    DETAIL_CONTRACT_COMMUNICATE = (504, "enum.xbbRefType.name.detail_contract_communicate", "detailContractCommunicate")
    DETAIL_OPPORTUNITY_COMMUNICATE = (505, "enum.xbbRefType.name.detail_opportunity_communicate", "detailOpportunityCommunicate")
    DETAIL_CONTACT_COMMUNICATE = (506, "enum.xbbRefType.name.detail_contact_communicate", "detailContactCommunicate")
    DETAIL_SUPPLIER_COMMUNICATE = (507, "enum.xbbRefType.name.detail_supplier_communicate", "detailSupplierCommunicate")
    DETAIL_PURCHASE_COMMUNICATE = (508, "enum.xbbRefType.name.detail_purchase_communicate", "detailPurchaseCommunicate")
    DETAIL_QUOTATION_COMUNICATE = (509, "enum.xbbRefType.name.detail_quotation_comunicate", "detailQuotationCommunicate")
    DETAIL_CLUE_COMUNICATE = (520, "enum.xbbRefType.name.detail_clue_comunicate", "detailClueCommunicate")
    CUSTOMER_COMMUNICATE_SUBFORM = (510, "enum.xbbRefType.name.customer_communicate_subform", "customerCommunicateSubform")
    SUPPLIER_COMMUNICATE_SUBFORM = (511, "enum.xbbRefType.name.supplier_communicate_subform", "supplierCommunicateSubform")
    COMMUNICATE_PLAN = (601, "enum.xbbRefType.name.communicate_plan", "communicatePlan")
    COMMUNICATE_PLAN_TEAM = (602, "enum.xbbRefType.name.communicate_plan_team", "communicatePlanTeam")
    COMMUNICATE_PLAN_SUBFORM = (603, "enum.xbbRefType.name.communicate_plan_subform", "communicatePlanSubform")
    PAYMENT_MANAGEMENT = (700, "enum.xbbRefType.name.payment_management", "paymentManagement")
    PAYMENT = (701, "enum.xbbRefType.name.payment", "payment")
    PAYMENT_SHEET = (702, "enum.xbbRefType.name.payment_sheet", "paymentSheet")
    RED_PAYMENT_SHEET = (703, "enum.xbbRefType.name.red_payment_sheet", "redPaymentSheet")
    BAD_DEBT = (704, "enum.xbbRefType.name.bad_debt", "badDebt")
    PAYMENT_REMIND = (705, "enum.xbbRefType.name.payment_remind", "paymentRemind")
    PAYMENT_OVERDUE = (706, "enum.xbbRefType.name.payment_overdue", "paymentOverdue")
    PAYMENT_TEAM = (707, "enum.xbbRefType.name.payment_team", "paymentTeam")
    PREPAYMENT = (708, "enum.xbbRefType.name.prepayment", "prepayment")
    WRITE_OFF_PREPAYMENT = (709, "enum.xbbRefType.name.write_off_prepayment", "writeOffPrepayment")
    RED_WRITE_OFF_PREPAYMENT = (710, "enum.xbbRefType.name.red_write_off_prepayment", "redWriteOffPrepayment")
    RED_PREPAYMENT = (711, "enum.xbbRefType.name.red_prepayment", "redPrepayment")
    PREPAYMENT_BALANCE = (712, "enum.xbbRefType.name.prepayment_balance", "prepaymentBalance")
    PREPAYMENT_BALANCE_TEAM = (713, "enum.xbbRefType.name.prepayment_balance_team", "prepaymentBalanceTeam")
    PAYMENT_SHEET_TEAM = (714, "enum.xbbRefType.name.payment_sheet_team", "paymentSheetTeam")
    RED_RECEIVABLES = (715, "enum.xbbRefType.name.red_receivables", "redReceivables")
    PAYMENT_SHEET_SUBFORM = (716, "enum.xbbRefType.name.payment_sheet_subform", "paymentSheetSubform")
    PAYMENT_SUBFORM = (717, "enum.xbbRefType.name.payment_subform", "paymentSubform")
    RED_WRITE_OFF_BALANCE = (718, "enum.xbbRefType.name.red_write_off_balance", "redWriteOffBalance")
    PAY_MANAGEMENT = (800, "enum.xbbRefType.name.pay_management", "payManagement")
    PAY_PLAN = (801, "enum.xbbRefType.name.pay_plan", "payPlan")
    PAY_SHEET = (802, "enum.xbbRefType.name.pay_sheet", "paySheet")
    PAY_PLAN_TEAM = (803, "enum.xbbRefType.name.pay_plan_team", "payPlanTeam")
    WRITE_OFF_PREPAY = (804, "enum.xbbRefType.name.write_off_prepay", "writeOffPrepay")
    PREPAY = (805, "enum.xbbRefType.name.prepay", "prepay")
    RED_WRITE_OFF_PAY = (806, "enum.xbbRefType.name.red_write_off_pay", "redWriteOffPay")
    RED_WRITE_OFF_PREPAY = (807, "enum.xbbRefType.name.red_write_off_prepay", "redWriteOffPrepay")
    RED_PREPAY = (808, "enum.xbbRefType.name.red_prepay", "redPrepay")
    BAD_PAY = (809, "enum.xbbRefType.name.bad_pay", "badPay")
    PREPAY_BALANCE = (810, "enum.xbbRefType.name.prepay_balance", "prepayBalance")
    PREPAY_BALANCE_TEAM = (811, "enum.xbbRefType.name.prepay_balance_team", "prepayBalanceTeam")
    PAY_PLAN_REMIND = (812, "enum.xbbRefType.name.pay_plan_remind", "payPlanRemind")
    PAY_PLAN_OVERDUE = (813, "enum.xbbRefType.name.pay_plan_overdue", "payPlanOverdue")
    PAY_SHEET_TEAM = (814, "enum.xbbRefType.name.pay_sheet_team", "payPlanSheetTeam")
    PAY_SHEET_SUBFORM = (815, "enum.xbbRefType.name.pay_sheet_subform", "paySheetSubform")
    PAY_PLAN_SUBFORM = (816, "enum.xbbRefType.name.pay_plan_subform", "payPlanSubform")
    INVOICE = (901, "enum.xbbRefType.name.invoice", "invoice")
    RED_INVOICE = (902, "enum.xbbRefType.name.red_invoice", "redInvoice")
    PURCHASE_INVOICE = (903, "enum.xbbRefType.name.purchase_invoice", "purchaseInvoice")
    RED_PURCHASE_INVOICE = (904, "enum.xbbRefType.name.red_purchase_invoice", "redPurchaseInvoice")
    INVOICE_SUBFORM = (905, "enum.xbbRefType.name.invoice_subform", "invoiceSubform")
    PURCHASE_INVOICE_SUBFORM = (906, "enum.xbbRefType.name.purchase_invoice_subform", "purchaseInvoiceSubform")
    INVOICE_EXPRESS = (907, "enum.xbbRefType.name.invoice_express", "invoiceExpress")
    PURCHASE_INVOICE_EXPRESS = (908, "enum.xbbRefType.name.purchase_invoice_express", "purchaseInvoiceExpress")
    SUPPLIER = (1001, "enum.xbbRefType.name.supplier", "supplier")
    SUPPLIER_CONTACT = (1002, "enum.xbbRefType.name.supplier_contact", "supplierContact")
    SUPPLIER_TEAM = (1003, "enum.xbbRefType.name.supplier_team", "supplierTeam")
    SUPPLIER_CONTACT_TEAM = (1004, "enum.xbbRefType.name.supplier_contact_team", "supplierContactTeam")
    SUPPLIER_PRODUCT = (1005, "enum.xbbRefType.name.supplier_product", "supplierProduct")
    SUPPLIER_CONTACT_SUBFORM = (1006, "enum.xbbRefType.name.supplier_contact_subform", "supplierContactSubform")
    SUPPLIER_SUBFORM = (1007, "enum.xbbRefType.name.supplier_subform", "supplierSubform")
    PURCHASE_MANAGEMENT = (1100, "enum.xbbRefType.name.purchase_management", "purchaseManagement")
    PURCHASE = (1101, "enum.xbbRefType.name.purchase", "purchase")
    WAIT_PURCHASE = (1102, "enum.xbbRefType.name.wait_purchase", "wait_purchase")
    PURCHASE_TEAM = (1103, "enum.xbbRefType.name.purchase_team", "purchaseTeam")
    PURCHASE_PRODUCT = (1104, "enum.xbbRefType.name.purchase_product", "purchaseProduct")
    WAIT_PURCHASE_CONTRACT = (1105, "enum.xbbRefType.name.wait_purchase_contract", "wait_purchase_contract")
    WAIT_PURCHASE_PRODUCT = (1106, "enum.xbbRefType.name.wait_purchase_product", "wait_purchase_product")
    PURCHASE_SUBFORM = (1107, "enum.xbbRefType.name.purchase_subform", "purchaseSubform")
    SMART_REPLENISHMENT = (1108, "enum.xbbRefType.name.smart_replenishment", "smartReplenishment")
    RETURNED_PURCHASE = (1201, "enum.xbbRefType.name.returned_purchase", "returnedPurchase")
    RETURNEDPURCHASE_PRODUCT = (1202, "enum.xbbRefType.name.returnedpurchase_product", "returnedPurchase_product")
    RETURNED_PURCHASE_SUBFORM = (1203, "enum.xbbRefType.name.returned_purchase_subform", "returnedPurchaseSubform")
    INVENTORY_MANAGEMENT = (1300, "enum.xbbRefType.name.inventory_management", "inventoryManagement")
    ASSEMBLE = (1301, "enum.xbbRefType.name.assemble", "assemble")
    ASSEMBLE_PRODUCT = (1302, "enum.xbbRefType.name.assemble_product", "assemble_product")
    ASSEMBLE_INPRODUCTS = (1303, "enum.xbbRefType.name.assemble_inproducts", "assembleInProducts")
    ASSEMBLE_SUBFORM = (1304, "enum.xbbRefType.name.assemble_subform", "assembleSubform")
    INSTOCK = (1401, "enum.xbbRefType.name.instock", "instockManagement")
    INSTOCK_PRODUCT = (1402, "enum.xbbRefType.name.instock_product", "instock_product")
    WAIT_INSTOCK_PURCHASE = (1403, "enum.xbbRefType.name.wait_instock_purchase", "wait_instock_purchase")
    PURCHASE_INSTOCK = (1404, "enum.xbbRefType.name.purchase_instock", "purchaseInstock")
    REFUND_INSTOCK = (1405, "enum.xbbRefType.name.refund_instock", "refundInstock")
    OTHER_INSTOCK = (1406, "enum.xbbRefType.name.other_instock", "instock")
    PRODUCTION_INSTOCK = (1407, "enum.xbbRefType.name.production_instock", "productionInstock")
    RETURNED_MATERIEL_INSTOCK = (1408, "enum.xbbRefType.name.returned_materiel_instock", "returnedMaterielInstock")
    INSTOCK_SUBFORM = (1409, "enum.xbbRefType.name.instock_subform", "instockSubform")
    OUTSTOCK = (1501, "enum.xbbRefType.name.outstock", "outstockManagement")
    OUTSTOCK_PRODUCT = (1502, "enum.xbbRefType.name.outstock_product", "outstock_product")
    WAIT_OUTSTOCK = (1503, "enum.xbbRefType.name.wait_outstock", "wait_outstock")
    CONTRACT_OUTSTOCK = (1504, "enum.xbbRefType.name.contract_outstock", "contractOutstock")
    RETURNED_PURCHASE_OUTSTOCK = (1505, "enum.xbbRefType.name.returned_purchase_outstock", "returnedPurchaseOutstock")
    OTHER_OUTSTOCK = (1506, "enum.xbbRefType.name.other_outstock", "outstock")
    PRODUCTION_MATERIEL_OUTSTOCK = (
    1507, "enum.xbbRefType.name.production_materiel_outstock", "productionMaterielOutstock")
    WORK_ORDER_OUTSTOCK = (1508, "enum.xbbRefType.name.work_order_outstock", "workOrderOutstock")
    OUTSTOCK_SUBFORM = (1509, "enum.xbbRefType.name.outstock_subform", "outstockSubform")
    TRANSFER = (1601, "enum.xbbRefType.name.transfer", "transfer")
    TRANSFER_PRODUCT = (1602, "enum.xbbRefType.name.transfer_product", "transfer_product")
    TRANSFER_SUBFORM = (1603, "enum.xbbRefType.name.transfer_subform", "transferSubform")
    INVENTORY = (1701, "enum.xbbRefType.name.inventory", "inventory")
    INVENTORY_PRODUCT = (1702, "enum.xbbRefType.name.inventory_product", "inventory_product")
    INVENTORY_SUBFORM = (1703, "enum.xbbRefType.name.inventory_subform", "inventorySubform")
    WAREHOUSE = (1801, "enum.xbbRefType.name.warehouse", "warehouse")
    WAREHOUSE_PRODUCT = (1802, "enum.xbbRefType.name.warehouse_product", "warehouse_product")
    WAREHOUSE_TEAM = (1803, "enum.xbbRefType.name.warehouse_team", "warehouseTeam")
    WAREHOUSE_SUBFORM = (1804, "enum.xbbRefType.name.warehouse_subform", "warehouseSubform")
    STOCK_SEARCH = (1901, "enum.xbbRefType.name.stock_search", "stockSearch")
    WARNING_SEARCH = (1902, "enum.xbbRefType.name.warning_search", "warningSearch")
    GUARANTEE_SEARCH = (1903, "enum.xbbRefType.name.guarantee_search", "guaranteeSearch")
    STOCK_FLOW_BILL = (1904, "enum.xbbRefType.name.stock_flow_bill", "stockFlowBill")
    STOCK_STANDING_BOOK = (1905, "enum.xbbRefType.name.stock_standing_book", "stockStandingBook")
    SEQ_SEARCH = (1906, "enum.xbbRefType.name.seq_search", "productSerialBalance")
    BATCH_FLOW_BILL = (1907, "enum.xbbRefType.name.batch_flow_bill", "batchFlowBill")
    COST_ADJUST = (1908, "enum.xbbRefType.name.cost_adjust", "costAdjust")
    COST_ADJUST_PRODUCT = (1909, "enum.xbbRefType.name.cost_adjust_product", "costAdjustProduct")
    COST_ADJUST_SUBFORM = (1910, "enum.xbbRefType.name.cost_adjust_subform", "costAdjustSubform")
    SIGNIN = (2001, "enum.xbbRefType.name.signin", "signIn")
    WORK_REPORT = (2101, "enum.xbbRefType.name.work_report", "workReport")
    WORKREPORT_DAILY = (2102, "enum.xbbRefType.name.workreport_daily", "workReportDaily")
    WORKREPORT_WEEKLY = (2103, "enum.xbbRefType.name.workreport_weekly", "workReportWeekly")
    WORKREPORT_MONTHLY = (2104, "enum.xbbRefType.name.workreport_monthly", "workReportMonthly")
    WORKREPORT_STATISIC = (2105, "enum.xbbRefType.name.workreport_statisic", "workReportDailyStatisic")
    WORK_REPORT_SUBFORM = (2106, "enum.xbbRefType.name.work_report_subform", "workReportSubform")
    APPROVAL = (2201, "enum.xbbRefType.name.approval", "approval")
    WORKFLOW = (2202, "enum.xbbRefType.name.workflow", "workflow")
    WORK_ORDER = (2301, "enum.xbbRefType.name.work_order", "workOrder")
    WORK_ORDER_TEAM = (2302, "enum.xbbRefType.name.work_order_team", "workOrderTeam")
    WORK_ORDER_CC = (2303, "enum.xbbRefType.name.work_order_cc", "workOrderCc")
    WORK_ORDER_EVALUATION = (2304, "enum.xbbRefType.name.work_order_evaluation", "workOrderEvaluation")
    WORK_ORDER_ROB = (2305, "enum.xbbRefType.name.work_order_rob", "workOrderRob")
    WORK_ORDER_OPERATION = (2306, "enum.xbbRefType.name.work_order_operation", "workOrderOperation")
    WORK_ORDER_SUBFORM = (2307, "enum.xbbRefType.name.work_order_subform", "workOrderSubform")
    PRODUCT = (2401, "enum.xbbRefType.name.product", "product")
    PRODUCT_TEAM = (2402, "enum.xbbRefType.name.product_team", "productTeam")
    PRODUCT_WAREHOUSE = (2403, "enum.xbbRefType.name.product_warehouse", "productWarehouse")
    PRODUCT_STOCK_INFO = (2404, "enum.xbbRefType.name.product_stock_info", "productStockInfo")
    BOMFISH_PRODUCT = (2405, "enum.xbbRefType.name.bomfish_product", "bomfishProduct")
    SELECT_PRODUCT = (2406, "enum.xbbRefType.name.select_product", "selectProduct")
    PRODUCT_SUBFORM = (2407, "enum.xbbRefType.name.product_subform", "productSubform")
    PRICE_SET_PRODUCT = (2408, "enum.xbbRefType.name.price_product", "priceProduct")
    PRODUCT_CATEGORY = (2409, "enum.xbbRefType.name.product_category", "productCategory")
    STOCK_PRODUCT = (2501, "enum.xbbRefType.name.stock_product", "stockProduct")
    BOM_BILL = (2601, "enum.xbbRefType.name.bom_bill", "bomBill")
    BOM_BILL_PRODUCT = (2602, "enum.xbbRefType.name.bom_bill_product", "BOMbill_product")
    BOM_BILL_TEAM = (2603, "enum.xbbRefType.name.bom_bill_team", "bomBillTeam")
    BOM_BILL_SUBFORM = (2604, "enum.xbbRefType.name.bom_bill_subform", "bomBillSubform")
    SIMULATED_PRODUCTION = (2701, "enum.xbbRefType.name.simulated_production", "simulatedProduction")
    PRODUCTION_MANAGEMENT = (2800, "enum.xbbRefType.name.production_management", "productionManagement")
    PRODUCTION_ORDER = (2801, "enum.xbbRefType.name.production_order", "productionOrder")
    PRODUCTION_ORDER_TEAM = (2802, "enum.xbbRefType.name.production_order_team", "productionOrderTeam")
    WAIT_PRODUCE = (2803, "enum.xbbRefType.name.wait_produce", "wait_produce")
    PRODUCTION_ORDER_PRODUCT = (2804, "enum.xbbRefType.name.production_order_product", "productionOrderProduct")
    WAIT_PRODUCE_CONTRACT = (2805, "enum.xbbRefType.name.wait_produce_contract", "wait_produce_contract")
    WAIT_PRODUCE_PRODUCT = (2806, "enum.xbbRefType.name.wait_produce_product", "wait_produce_product")
    PRODUCTION_ORDER_SUBFORM = (2807, "enum.xbbRefType.name.production_order_subform", "productionOrderSubform")
    STATISTICS = (2901, "enum.xbbRefType.name.statistics", "statistics")
    PERFORMANCE = (3001, "enum.xbbRefType.name.performance", "performance")
    BI_DATA_WAREHOUSE = (3101, "enum.xbbRefType.name.bi_data_warehouse", "biDataWareHouse")
    SALES_REPORT_ENTITY = (3201, "enum.xbbRefType.name.sales_report_entity", "salesReportEntity")
    GROUP_MESSAGE = (33, "enum.xbbRefType.name.group_message", "groupMessage")
    SEND_MESSAGE = (3301, "enum.xbbRefType.name.send_message", "sendMessage")
    RECORD_VIEW = (3302, "enum.xbbRefType.name.record_view", "recordView")
    CONFIG_INFORMATION = (3303, "enum.xbbRefType.name.config_information", "configInformation")
    RECHARGE_RECORD = (3304, "enum.xbbRefType.name.recharge_record", "rechargeRecord")
    REPLY_VIEW = (3305, "enum.xbbRefType.name.reply_view", "replyView")
    AI_ASSISTANT = (3401, "enum.xbbRefType.name.ai_assistant", "aiAssistant")
    APP_STORE = (3501, "enum.xbbRefType.name.app_store", "appStore")
    CALL_CENTER = (3601, "enum.xbbRefType.name.call_center", "callCenter")
    CALL_CENTER_DU_YAN = (3602, "enum.xbbRefType.name.call_center_du_yan", "duyan")
    CALL_CENTER_DINGTALK = (3603, "enum.xbbRefType.name.call_center_dingtalk", "dingtalk")
    CALL_CENTER_COMMON_CALL = (3604, "enum.xbbRefType.name.call_center_common_call", "commonCall")
    CALL_CENTER_XBB = (3605, "enum.xbbRefType.name.call_center_xbb", "xbb")
    CALL_CENTER_CALL_LOG = (3606, "enum.xbbRefType.name.call_center_call_log", "callLog")
    CALL_CENTER_ALI_YUN = (3612, "enum.xbbRefType.name.call_center_ali_yun", "AICallDetailed")
    IMPORT_AND_EXPORT = (3700, "enum.xbbRefType.name.import_and_export", "importAndExport")
    EXPORT = (3701, "enum.xbbRefType.name.export", "export")
    EXPORT_FAIL = (3702, "enum.xbbRefType.name.export_fail", "export_fail")
    FUND_MANAGEMENT = (3900, "enum.xbbRefType.name.fund_management", "fundManagement")
    SET_MEAL = (4000, "enum.xbbRefType.name.set_meal", "setMeal")
    PUSH_NOTIFY = (4100, "enum.xbbRefType.name.push_notify", "pushNotify")
    LOCATION = (4200, "enum.xbbRefType.name.location", "location")
    DING = (4300, "enum.xbbRefType.name.ding", "ding")
    DYNAMIC = (4400, "enum.xbbRefType.name.dynamic", "dynamic")
    USER = (4500, "enum.xbbRefType.name.user", "user")
    SEARCH_CUSTOMER = (4600, "enum.xbbRefType.name.search_customer", "searchCustomer")
    EXCAVATE_CLUE = (4601, "enum.xbbRefType.name.excavate_clue", "excavateClue")
    COLLECTOR = (4602, "enum.xbbRefType.name.collector", "collector")
    INDIVIDUAL_CLUE = (4603, "enum.xbbRefType.name.individual_clue", "individualClue")
    AUTHORITY_MANAGE = (4604, "enum.xbbRefType.name.authority_manage", "authorityManage")
    RECYCLE_BIN = (4606, "enum.xbbRefType.name.recycle_bin", "recycleBin")
    QUOTATION = (4700, "enum.xbbRefType.name.quotation", "quotation")
    QUOTATION_TEAM = (4701, "enum.xbbRefType.name.quotation_team", "quotationTeam")
    QUOTATION_PRODUCT = (4702, "enum.xbbRefType.name.quotation_product", "quotationProduct")
    QUOTATION_REMIND = (4703, "enum.xbbRefType.name.quotation_remind", "quotationRemind")
    QUOTATION_SUBFORM = (4704, "enum.xbbRefType.name.quotation_subform", "quotationSubform")
    ORI_STOCK = (4800, "enum.xbbRefType.name.ori_stock", "oriStock")
    FUND_ACCOUNT_FLOW = (4900, "enum.xbbRefType.name.fund_account_flow", "fundAccountFlow")
    DISTRIBUTOR_FUND_ACCOUNT = (4910, "enum.xbbRefType.name.distributor_fund_account", "distributorFundAccount")
    PAYMENT_TASK = (5301, "enum.xbbRefType.name.payment_task", "paymentTask")
    PAYMENT_TASK_TEAM = (5302, "enum.xbbRefType.name.payment_task_team", "paymentTaskTeam")
    PAYMENT_TASK_SUBFORM = (5304, "enum.xbbRefType.name.payment_task_subform", "paymentTaskSubform")
    STATEMENT = (5400, "enum.xbbRefType.name.statement", "statement")
    CUSTOMER_STATEMENT = (5401, "enum.xbbRefType.name.customer_statement", "customerStatement")
    CUSTOMER_STATEMENT_SNAPSHOT = (
    5402, "enum.xbbRefType.name.customer_statement_snapshot", "customerStatementSnapshot")
    CUSTOMER_STATEMENT_STATISTIC = (5403, "enum.xbbRefType.name.statement_list", "customerStatementStatistic")
    CREDIT_MANAGEMENT = (5500, "enum.xbbRefType.name.credit_management", "creditManagement")
    CREDIT_LIMIT = (5510, "enum.xbbRefType.name.credit_limit", "creditLimit")
    CREDIT_TEMPORARY_LIMIT = (5520, "enum.xbbRefType.name.credit_temporary_limit", "creditTemporaryLimit")
    CREDIT_TEMPORARY_LIMIT_SUBFORM = (
    5521, "enum.xbbRefType.name.credit_temporary_limit_subform", "creditTemporaryLimitSubform")
    CREDIT_FIXED_LIMIT = (5530, "enum.xbbRefType.name.credit_fixed_limit", "creditFixedLimit")
    CREDIT_FIXED_LIMIT_SUBFORM = (5531, "enum.xbbRefType.name.credit_fixed_limit_subform", "creditFixedLimitSubform")
    CREDIT_CARD_BILL = (5540, "enum.xbbRefType.name.credit_card_bill", "creditCardBill")
    ONLINE_PAYMENT_FLOW = (5600, "enum.xbbRefType.name.online_payment_flow", "onlinePaymentFlow")
    OTHER_FUND_MANAGEMENT = (5700, "enum.xbbRefType.name.other_fund_management", "otherFundManagement")
    OTHER_INCOME = (5710, "enum.xbbRefType.name.other_income", "otherIncome")
    RED_OTHER_INCOME = (5711, "enum.xbbRefType.name.red_other_income", "redOtherIncome")
    OTHER_INCOME_SUBFORM = (5712, "enum.xbbRefType.name.other_income_subform", "otherIncomeSubform")
    OTHER_EXPENSE = (5750, "enum.xbbRefType.name.other_expense", "otherExpense")
    RED_OTHER_EXPENSE = (5751, "enum.xbbRefType.name.red_other_expense", "redOtherExpense")
    OTHER_EXPENSE_SUBFORM = (5752, "enum.xbbRefType.name.other_expense_subform", "otherExpenseSubform")
    FUND_TRANSFER = (5800, "enum.xbbRefType.name.fund_transfer", "fundTransfer")
    FUND_TRANSFER_SUBFORM = (5801, "enum.xbbRefType.name.fund_transfer_subform", "fundTransferSubform")
    ESIGN = (6000, "enum.xbbRefType.name.esign", "esign")
    ESIGN_RECHARGE = (6001, "enum.xbbRefType.name.esign_recharge", "esignRecharge")
    ESIGN_CORP_INFO = (6002, "enum.xbbRefType.name.esign_corp_info", "esignCorpInfo")
    ESIGN_OTHER_SET = (6003, "enum.xbbRefType.name.esign_other_set", "esignOtherSet")
    ESIGN_COMMON = (6010, "enum.xbbRefType.name.esign_common", "esignCommon")
    DATA_CENTER = (6100, "enum.xbbRefType.name.data_center", "dataCenter")
    DATA_WARNING = (6101, "enum.xbbRefType.name.data_warning", "dataWarning")
    DATA_SET = (6300, "enum.xbbRefType.name.data_set", "dataSet")
    AI_CENTER = (6400, "enum.xbbRefType.name.ai_center", "aiCenter")
    AI_MANAGE = (6401, "enum.xbbRefType.name.ai_manage", "aiManage")
    DATA_FACTORY = (6500, "enum.xbbRefType.name.data_factory", "dataFactory")
    DATA_OVERVIEW = (6501, "enum.xbbRefType.name.data_overview", "dataOverview")
    DATA_IMPORT = (6502, "enum.xbbRefType.name.data_import", "dataImport")
    DATA_CALLOUT = (6503, "enum.xbbRefType.name.data_callout", "dataCallout")
    TRAIN_MODEL = (6504, "enum.xbbRefType.name.train_model", "trainModel")
    LABEL_MANAGE = (6505, "enum.xbbRefType.name.label_manage", "labelManage")
    DATA_FACEPLATE = (6600, "enum.xbbRefType.name.data_faceplate", "dataFaceplate")
    MARKETING_MANAGEMENT = (9000, "enum.xbbRefType.name.marketing_management", "marketingManagement")
    MARKETING_TOOL = (9001, "enum.xbbRefType.name.marketing_tool", "marketingTool")
    MARKETING_ACTIVITY = (9002, "enum.xbbRefType.name.marketing_activity", "marketingActivity")
    MARKETING_ACTIVITY_MANAGEMENT = (
    9003, "enum.xbbRefType.name.marketing_activity_management", "marketingActivityManagement")
    FULL_DISCOUNT_COUPON = (9004, "enum.xbbRefType.name.full_discount_coupon", "fullDiscountCoupon")
    PROMOTION_TOOL = (9005, "enum.xbbRefType.name.promotion_tool", "promotionTool")
    PROMOTION_ACTIVITY = (9006, "enum.xbbRefType.name.promotion_activity", "promotionActivity")
    PROMOTION_ACTIVITY_MANAGEMENT = (
    9007, "enum.xbbRefType.name.promotion_activity_management", "promotionActivityManagement")
    SPECIAL_GOODS = (9008, "enum.xbbRefType.name.special_product", "specialProducts")
    WRITE_OFF_RECORD = (9009, "enum.xbbRefType.name.write_off_record", "writeOffRecord")
    DISTRIBUTOR_COUPON = (9010, "enum.xbbRefType.name.distributor_coupon", "distributorCoupon")
    DISTRIBUTOR_ACCOUNT = (9500, "enum.xbbRefType.name.distributor_account", "account")
    DISTRIBUTOR_MANAGEMENT = (9501, "enum.xbbRefType.name.distributor_management", "distributorManagement")
    DISTRIBUTOR_CONTACT = (9502, "enum.xbbRefType.name.distributor_contact", "distributorContact")
    DISTRIBUTOR_COMMUNICATE = (9503, "enum.xbbRefType.name.distributor_communicate", "distributorCommunicate")
    ORDER = (9510, "enum.xbbRefType.name.order", "order")
    RETURN = (9511, "enum.xbbRefType.name.return", "return")
    ORDER_OUTSTOCK = (9512, "enum.xbbRefType.name.orderOutStock", "orderOutStock")
    DISTRIBUTOR_ORDER = (9513, "enum.xbbRefType.name.distributorOrder", "distributorOrder")
    DYNAMIC_DATA = (10000, "enum.xbbRefType.name.dynamic.data", "dynamicData")
    DEFAULT_DATA = (10001, "enum.xbbRefType.name.dynamic.data", "defaultData")
    BUNDLE = (7000, "enum.xbbRefType.name.bundle", "bundle")
    SALE_BUNDLE = (7001, "enum.xbbRefType.name.sale_bundle", "sale_bundle")
    COOL_APP = (7002, "enum.xbbRefType.name.cool_app", "coolApp")
    CLUE = (8000, "enum.xbbRefType.name.clue", "clue")
    ALL_CLUE = (8001, "enum.xbbRefType.name.all_clue", "allClue")
    CLUE_PUBLIC = (8002, "enum.xbbRefType.name.clue_public", "cluePublic")
    CLUE_RECYCLE = (8003, "enum.xbbRefType.name.clue_recycle", "clueRecycle")
    CLUE_TEAM = (8004, "enum.xbbRefType.name.clue_team", "clueTeam")
    CLUE_STAGE = (8005, "enum.xbbRefType.name.clue_stage", "clueStage")
    CLUE_DUPLICATE = (8006, "enum.xbbRefType.name.clue_duplicate", "clueDuplicate")
    CLUE_BACK_REMIND = (8007, "enum.xbbRefType.name.clue_back_remind", "clueBackRemind")
    CLUE_SUBFORM = (8008, "enum.xbbRefType.name.clue_subform", "clueSubform")
    CLUE_TRANSFER = (8009, "enum.xbbRefType.name.clue_transfer", "clueTransfer")
    CLUE_TRANSFER_REMIND = (8010, "enum.xbbRefType.name.clue_transfer_remind", "clueTransferRemind")
    CLUE_STAGE_LOG = (8011, "enum.xbbRefType.name.clue_stage_log", "clueStageLog")
    AD_HELPER = (8012, "enum.xbbRefType.name.ad_helper", "adHelper")
    MARKET_ACTIVITY = (8100, "enum.xbbRefType.name.market_activity", "marketActivity")
    MARKET_ACTIVITY_TEAM = (8101, "enum.xbbRefType.name.market_activity_team", "marketActivityTeam")
    MARKET_ACTIVITY_SUBFORM = (8102, "enum.xbbRefType.name.market_activity_subform", "marketActivitySubform")
    MARKET_ACTIVITY_STATIC = (8103, "enum.xbbRefType.name.market_activity_static", "marketActivityStatic")
    SLA_LOG = (8200, "enum.xbbRefType.name.sla_log", "slaLog")
    SLA_LOG_TEAM = (8201, "enum.xbbRefType.name.sla_log_team", "slaLogTeam")
    WORKFLOW_SEND_MESSAGE = (100800, "enum.xbbRefType.name.workflow_send_message", "workflowSendMessage")
    WORKFLOW_SEND_SMS = (100801, "enum.xbbRefType.name.workflow_send_sms", "workflowSendSms")
    WORKFLOW_APPROVAL_TIMEOUT_REMIND = (100802, "enum.xbbRefType.name.workflow_approval_timeout_remind", "workflowApprovalTimeoutRemind")
    WORKFLOW_EXCEPTION_PUSH = (100803, "enum.xbbRefType.name.workflow_exception_push", "workflowExceptionPush")
    WORKFLOW_TRIGGER_QUANTITY_WARNING_PUSH = (100804, "enum.xbbRefType.name.workflow_exception_push", "workflowTriggerQuantityWarningPush")
    FINE_CLUE = (20000, "enum.xbbRefType.name.fine_clue", "fineClue")
    FINE_CLUE_QUERY_COMPANY = (20001, "enum.xbbRefType.name.fine_clue_query_company", "fineClueQueryCompany")
    FINE_CLUE_QUERY_CLUE = (20002, "enum.xbbRefType.name.fine_clue_query_clue", "fineClueQueryClue")
    FINE_CLUE_MAP_QUERY = (20003, "enum.xbbRefType.name.fine_clue_map_query", "fineClueMapQuery")
    FINE_CLUE_BATCH_QUERY = (20004, "enum.xbbRefType.name.fine_clue_batch_query", "fineClueBatchQuery")
    FINE_CLUE_PERMISSIONS = (20005, "enum.xbbRefType.name.fine_clue_permissions", "finCluePermissions")
    FINE_CLUE_QUERY_STORE = (20006, "enum.xbbRefType.name.fine_clue_query_store", "fineClueQueryStore")
    STAGE_TIMEOUT_REMIND = (50005, "enum.xbbRefType.name.stageTimeoutRemind", "stageTimeoutRemind")
    PAAS_STAGE = (50006, "enum.xbbRefType.name.paasStage", "paasStage")
    STAGE_LOG = (50007, "enum.xbbRefType.name.stage_log", "stageLog")
    KNOWLEDGE_BASE = (20100, "enum.xbbRefType.name.knowledge_base", "knowledgeBase")
    COMPETITOR = (20200, "enum.xbbRefType.name.competitor", "competitor")
    COMPETITOR_ANALYSIS = (20201, "enum.xbbRefType.name.competitor_analysis", "competitorAnalysis")
    COMPETITOR_TEAM = (20202, "enum.xbbRefType.name.competitor_team", "competitorTeam")
    COMPETITOR_SUBFORM = (20203, "enum.xbbRefType.name.competitor_subform", "competitorSubform")
    CONTRACT_COMPARE = (20400, "enum.xbbRefType.name.contractCompare", "contractCompare")
    CONTRACT_COMPARE_RESULT = (20500, "enum.xbbRefType.name.contractCompareResult", "contractCompareResult")
    CONTRACT_COMPARE_MANAGE = (20501, "enum.xbbRefType.name.contractCompareManage", "contractCompareManage")
    CONTRACT_COMPARE_FORM = (20502, "enum.xbbRefType.name.contractCompareForm", "contractCompareForm")
    MULTIPLE_ADDRESS = (21200, "enum.xbbRefType.name.multipleAddress", "multipleAddress")

    ### 工单2.0 203xx
    # 工单中心
    WORK_ORDER_V2_CENTER = (20290, "enum.xbbRefType.name.work_order_v2_center", "workOrderV2Center")
    WORK_ORDER_V2_MANAGEMENT = (20291, "enum.xbbRefType.name.work_order_v2_management", "workOrderV2Management")
    # 新工单
    WORK_ORDER_V2 = (20300, "enum.xbbRefType.name.work_order_v2", "workOrderV2")
    WORK_ORDER_V2_TEAM = (20301, "enum.xbbRefType.name.work_order_v2_team", "workOrderV2Team")
    WORK_ORDER_V2_SUBFORM = (20302, "enum.xbbRefType.name.work_order_v2_subform", "workOrderV2Subform")
    WORK_ORDER_V2_PRODUCT = (20303, "enum.xbbRefType.name.work_order_v2_product", "workOrderV2Product")
    WORK_ORDER_V2_POOL = (20304, "enum.xbbRefType.name.work_order_v2_pool", "workOrderV2Pool")
    WORK_ORDER_V2_APPOINT = (20305, "enum.xbbRefType.name.work_order_v2_appoint", "workOrderV2Appoint")
    WORK_ORDER_V2_NODE_INFO = (20306, "enum.xbbRefType.name.work_order_v2", "workOrderV2NodeInfo")
    ALL_WORK_ORDER_V2 = (20307, "enum.xbbRefType.name.all_work_order_v2", "allWorkOrderV2")
    WORK_ORDER_V2_NODE_INFO_LOG_ITEM = (20308, "enum.xbbRefType.name.work_order_v2", "workOrderV2NodeInfoLogItem")
    WORK_ORDER_V2_TODO = (20309, "enum.xbbRefType.name.work_order_v2_todo", "workOrderV2Todo")
    # 工单设置
    WORK_ORDER_V2_SETTING = (20310, "enum.xbbRefType.name.work_order_v2_setting", "workOrderV2Setting")
    # 工单目录
    WORK_ORDER_V2_CATALOGUE = (20311, "enum.xbbRefType.name.all_work_order_v2_catalogue", "workOrderV2Catalogue")
    # 自助工单
    WORK_ORDER_V2_AUTO_ORDER = (20314, "enum.xbbRefType.name.all_work_order_v2_auto_order", "workOrderV2AutoOrder")
    # 评价设置
    WORK_ORDER_V2_EVALUATION_SETTING = (
    20312, "enum.xbbRefType.name.all_work_order_v2_evaluation_setting", "workOrderV2EvaluationSetting")
    # 回访工单
    WORK_ORDER_V2_VISIT_ORDER = (20313, "enum.xbbRefType.name.all_work_order_v2_visit_order", "workOrderV2VisitOrder")
    # 客户自助工单
    WORK_ORDER_V2_AUTO_WORK = (20315, "enum.xbbRefType.name.all_work_order_v2_auto_work", "workOrderV2AutoWork")
    # 自助门户
    WORK_ORDER_V2_AUTO_PORTAL = (20316, "enum.xbbRefType.name.all_work_order_v2_auto_portal", "workOrderV2AutoPortal")
    # SLA规则
    SLA_RULE = (20320, "enum.xbbRefType.name.sla_rule", "slaRule")
    # 服务项目
    SERVICE_PROJECT = (20330, "enum.xbbRefType.name.service_project", "serviceProject")
    SERVICE_PROJECT_TEAM = (20331, "enum.xbbRefType.name.service_project_team", "serviceProjectTeam")
    SERVICE_PROJECT_SUBFORM = (20332, "enum.xbbRefType.name.service_project_subform", "serviceProjectSubform")
    # 回执单
    RECEIPT_ORDER = (20340, "enum.xbbRefType.name.receipt_order", "receiptOrder")
    RECEIPT_ORDER_TEAM = (20342, "enum.xbbRefType.name.receipt_order_team", "receiptOrderTeam")
    RECEIPT_ORDER_SUBFORM = (20343, "enum.xbbRefType.name.receipt_order_subform", "receiptOrderSubform")
    RECEIPT_ORDER_PRODUCT = (20344, "enum.xbbRefType.name.receipt_order_product", "receiptOrderProduct")
    RECEIPT_ORDER_SERVICE = (20345, "enum.xbbRefType.name.receipt_order_service", "receiptOrderService")
    # 工单节点日志信息(自定义图表)
    WORK_ORDER_V2_NODE_LOG_INFO = (20350, "enum.xbbRefType.name.work_order_v2_node_log_info", "workOrderV2NodeLogInfo")
    # 服务评价
    WORK_ORDER_V2_SERVICE_EVALUATION = (
    20360, "enum.xbbRefType.name.work_order_v2_service_evaluation", "workOrderV2ServiceEvaluation")
    WORK_ORDER_V2_SERVICE_EVALUATION_TEAM = (
    20361, "enum.xbbRefType.name.work_order_v2_service_evaluation_team", "workOrderV2ServiceEvaluationTeam")
    # 客户资产
    WORK_ORDER_V2_CUSTOMER_ASSET = (20370, "enum.xbbRefType.name.work_order_v2_customer_asset", "customerAsset")
    WORK_ORDER_V2_CUSTOMER_ASSET_TEAM = (
    20371, "enum.xbbRefType.name.work_order_v2_customer_asset_team", "customerAssetTeam")
    WORK_ORDER_V2_CUSTOMER_ASSET_SUBFORM = (
    20372, "enum.xbbRefType.name.work_order_v2_customer_asset_subform", "customerAssetSubForm")
    WORK_ORDER_V2_AUTO_CUSTOMER_ASSET = (
    20373, "enum.xbbRefType.name.work_order_v2_auto_customer_asset", "autoCustomerAsset")
    WORK_ORDER_V2_CUSTOMER_ASSET_BATCH = (
    20374, "enum.xbbRefType.name.work_order_v2_customer_asset_batch", "customerAssetBatch")
    CONTRACT_TEMPLATE_BASE = (20700, "enum.xbbRefType.name.onlineEditor", "onlineEditor")

    # 全部项目
    PROJECT = (20800, "enum.xbbRefType.name.project", "project")
    PROJECT_PRODUCT = (20801, "enum.xbbRefType.name.projectProduct", "projectProduct")
    PROJECT_SUBFORM = (20802, "enum.xbbRefType.name.projectSubForm", "projectSubForm")
    PROJECT_TEAM = (20803, "enum.xbbRefType.name.projectTeam", "projectTeam")
    # 项目任务
    PROJECT_TASK = (20900, "enum.xbbRefType.name.projectTask", "projectTask")
    PROJECT_TASK_SUBFORM = (20901, "enum.xbbRefType.name.projectTaskSubForm", "projectTaskSubForm")
    PROJECT_TASK_TEAM = (20902, "enum.xbbRefType.name.projectTaskTeam", "projectTaskTeam")
    PROJECT_TASK_PROJECT = (20903, "enum.xbbRefType.name.projectTaskProject", "projectTaskProject")
    # 项目风险
    PROJECT_RISK = (21000, "enum.xbbRefType.name.projectRisk", "projectRisk")
    PROJECT_RISK_SUBFORM = (21001, "enum.xbbRefType.name.projectRiskSubForm", "projectRiskSubForm")
    PROJECT_RISK_TEAM = (21002, "enum.xbbRefType.name.projectRiskTeam", "projectRiskTeam")
    PROJECT_RISK_PROJECT = (21003, "enum.xbbRefType.name.projectRiskProject", "projectRiskProject")
    # 工时记录
    WORK_TIME_RECORD = (21100, "enum.xbbRefType.name.worktime_record", "workTimeRecord")
    WORK_TIME_RECORD_TEAM = (21101, "enum.xbbRefType.name.worktime_record_team", "workTimeRecordTeam")
    WORK_TIME_RECORD_SUBFORM = (21102, "enum.xbbRefType.name.worktime_record_subform", "workTimeRecordSubform")
    # 工时记录项目数据
    WORK_TIME_RECORD_PROJECT = (21103, "enum.xbbRefType.name.worktime_record_project", "workTimeRecordProject")
    # 待办-任务
    TODO_TASK = (21300, "enum.xbbRefType.name.todo_task", "projectToDo")
    # 员工个人仓
    PERSONAL_WAREHOUSE = (21600, "enum.xbbRefType.name.personalWarehouse", "personalWarehouse")
    PERSONAL_WAREHOUSE_TEAM = (21601, "enum.xbbRefType.name.personalWarehouseTeam", "personalWarehouseTeam")
    PERSONAL_WAREHOUSE_SUBFORM = (21602, "enum.xbbRefType.name.personalWarehouseSubForm", "personalWarehouseSubForm")
    # 工单领料单
    RECEIVE_MATERIAL = (21700, "enum.xbbRefType.name.receiveMaterial", "receiveMaterial")
    RECEIVE_MATERIAL_TEAM = (21701, "enum.xbbRefType.name.receiveMaterialTeam", "receiveMaterialTeam")
    RECEIVE_MATERIAL_SUBFORM = (21702, "enum.xbbRefType.name.receiveMaterialSubForm", "receiveMaterialSubForm")
    RECEIVE_MATERIAL_PRODUCT = (21703, "enum.xbbRefType.name.receiveMaterialProduct", "receiveMaterialProduct")
    # 工单退料单
    RETURN_MATERIAL = (21800, "enum.xbbRefType.name.returnMaterial", "returnMaterial")
    RETURN_MATERIAL_TEAM = (21801, "enum.xbbRefType.name.returnMaterialTeam", "returnMaterialTeam")
    RETURN_MATERIAL_SUBFORM = (21802, "enum.xbbRefType.name.returnMaterialSubForm", "returnMaterialSubForm")
    RETURN_MATERIAL_PRODUCT = (21803, "enum.xbbRefType.name.returnMaterialProduct", "returnMaterialProduct")
    # 服务报告
    SERVICE_REPORT = (21850, "enum.xbbRefType.name.serviceReport", "serviceReport")
    SERVICE_REPORT_TEAM = (21851, "enum.xbbRefType.name.serviceReportTeam", "serviceReportTeam")
    # 个人备件库查询
    PERSONAL_STOCK_SEARCH = (21900, "enum.xbbRefType.name.personalStockSearch", "personalStockSearch")
    # 备件出入库明细
    PERSONAL_STOCK_FLOW = (22000, "enum.xbbRefType.name.personalStockFlow", "personalStockFlow")
    # 备件消耗明细
    SPARE_PARTS_CONSUME_ITEM = (22100, "enum.xbbRefType.name.sparePartsConsumeItem", "sparePartsConsumeItem")
    # 备品备件
    SPARE_PARTS = (22101, "enum.xbbRefType.name.spareParts", "spareParts")
    # 门户访问记录
    PORTAL_ACCESS_RECORD = (23100, "enum.xbbRefType.name.portalAccessRecord", "userAccessRecord")

    # 智能表单
    INTELLIGENT_FORM = (20600, "enum.xbbRefType.name.intelligentForm", "intelligentForm")
    INTELLIGENT_FORM_MANAGEMENT = (20601, "enum.xbbRefType.name.intelligentFormManagement", "intelligentFormManagement")
    INTELLIGENT_FORM_MANAGEMENT_DATA = (20602, "enum.xbbRefType.name.intelligentFormManagementData", "intelligentFormManagementData")
    # 资源管理
    RESOURCE_MANAGEMENT = (22200, "enum.xbbRefType.name.resourceManagement", "resourceManagement")
    # 待办，保持和多平台待办业务类型一致
    TODO = (101500, "enum.xbbRefType.name.todo", "todo")
    # 工作任务
    WORK_TASK = (21500, "enum.xbbRefType.name.workTask", "workTask")
    WORK_TASK_TEAM = (21501, "enum.xbbRefType.name.workTask", "workTaskTeam")
    WORK_TASK_SUBFORM = (21502, "enum.xbbRefType.name.workTask", "workTaskSubForm")
    # 资产设置
    ASSETS_MANAGE = (22200, "enum.xbbRefType.name.assetsManage", "assetsManage")
    # 微信客服
    IM_V1_WECHAT_CUSTOMER_SERVICE = (24000, "enum.xbbRefType.name.imV1WechatCustomerService", "imV1WechatKf")
    IM_V1_ONLINE_STAGING = (24100, "enum.xbbRefType.name.onlineStaging", "onlineStaging")
    IM_V1_SIDEBAR = (24110, "enum.xbbRefType.name.imV1Sidebar", "imV1Sidebar")
    IM_V1_SIDEBAR_SERVICE = (24120, "enum.xbbRefType.name.imV1SidebarService", "imV1SidebarService")
    IM_V1_SESSION_RECORD = (24200, "enum.xbbRefType.name.imV1SessionRecord", "sessionRecord")
    IM_V1_SESSION_RECORD_USER = (24210, "enum.xbbRefType.name.imV1SessionRecordUser", "imV1SessionRecordUser")
    IM_V1_QUALITY_INSPECTION = (24300, "enum.xbbRefType.name.imV1QualityInspection", "qualityInspection")
    IM_V1_QUALITY_INSPECTION_USER = (24310, "enum.xbbRefType.name.imV1QualityInspectionUser", "imV1QualityInspectionUser")
    # 邮箱管理
    MAIL_MANAGE = (23000, "enum.xbbRefType.name.mailManage", "mailManage")
    # 邮件管理-邮件
    MAIL = (230001, "enum.xbbRefType.name.mail", "mail")
    CUSTOMER_COMMUNICATE_QUALITY = (250000, "enum.xbbRefType.name.customerCommunicateQuality", "customerCommunicateQuality")
    # Review
    OPPORTUNITY_REVIEW = (30101, "enum.xbbRefType.name.opportunityReview", "opportunityReview")

    def __init__(self, code, name, alias):
        self.code = code
        self.name = name
        self.alias = alias

    @classmethod
    def get_by_alias(cls, alias):
        for enum_member in cls:
            if enum_member.alias == alias:
                return enum_member
        return cls.UNKNOWN

    @classmethod
    def get_by_code(cls, code):
        for enum_member in cls:
            if enum_member.code == code:
                return enum_member
        return cls.UNKNOWN
